`timescale 1ns/1ps

// End-to-end board smoke test: UART prompt -> generation_controller ->
// transformer_engine -> weight ROM -> argmax -> UART TX.
//
// A tiny zero-filled model is used (all weights/biases zero), so every logit
// is zero and the argmax is token 0, which maps to '.'. The test only checks
// that a character is generated and returned, not model quality.

module tb_fpga_top;

    localparam DIM = 4;
    localparam HEADS = 2;
    localparam LEN = 4;
    localparam LAYERS = 1;
    localparam DFF = 4;
    localparam VOCAB = 8;
    localparam ROM_DEPTH = 4096;

    reg clk = 0;
    reg rst_n;
    reg uart_rx;
    wire uart_tx;
    wire [9:0] ledr;

    always #10 clk = ~clk;

    fpga_top #(
        .D_MODEL(DIM), .NUM_HEADS(HEADS), .MAX_SEQ_LEN(LEN), .NUM_LAYERS(LAYERS),
        .D_FF(DFF), .VOCAB_SIZE(VOCAB), .W_ADDR_WIDTH(12),
        .ROM_DEPTH(ROM_DEPTH), .ROM_MEM_FILE("no_such_file.hex"), .GEN_TOKENS(1),
        .TOP_K(1)
    ) dut (
        .CLOCK_50(clk),
        .KEY({3'b111, rst_n}),
        .UART_RXD(uart_rx),
        .UART_TXD(uart_tx),
        .LEDR(ledr)
    );

    // Zero the weight ROM so the engine produces all-zero logits (argmax = 0).
    integer i;
    initial begin
        for (i = 0; i < ROM_DEPTH; i = i + 1)
            dut.controller_inst.weight_rom_inst.mem[i] = 8'h00;
    end

    localparam CLOCKS_PER_BIT = 50000000 / 115200;
    localparam BIT_PERIOD = CLOCKS_PER_BIT * 20; // 20 ns clock period

    task send_uart_byte;
        input [7:0] data;
        integer b;
        begin
            uart_rx = 1'b0;
            #(BIT_PERIOD);
            for (b = 0; b < 8; b = b + 1) begin
                uart_rx = data[b];
                #(BIT_PERIOD);
            end
            uart_rx = 1'b1;
            #(BIT_PERIOD);
        end
    endtask

    task receive_uart_byte;
        output [7:0] data;
        integer b;
        begin
            wait (uart_tx == 1'b0);
            #(BIT_PERIOD / 2);
            #(BIT_PERIOD);
            for (b = 0; b < 8; b = b + 1) begin
                data[b] = uart_tx;
                #(BIT_PERIOD);
            end
            if (uart_tx !== 1'b1)
                $display("Warning: UART TX framing error (stop bit missing)");
        end
    endtask

    reg [7:0] rx_byte;

    initial begin
        rst_n = 0;
        uart_rx = 1'b1;
        #200 rst_n = 1;
        #200;

        // Prompt, then CR/LF to start decoding.
        send_uart_byte(8'h41); // 'A'
        send_uart_byte(8'h42); // 'B'
        send_uart_byte(8'h0A); // newline -> generate

        receive_uart_byte(rx_byte);
        $display("Generated byte: 0x%0h", rx_byte);
        if (rx_byte == 8'h2E) begin
            $display("TEST PASSED: generation returned '.' (argmax token 0)");
        end else begin
            $display("TEST FAILED: expected 0x2E, got 0x%0h", rx_byte);
            $fatal(1, "generation mismatch");
        end
        #1000 $finish;
    end

    initial begin #50000000; $fatal(1, "timeout"); end

endmodule
