"""Command-line entry point for the fpGPT host GUI.

Examples::

    python -m fgpt_gui                      # mock/echo, legacy link
    python -m fgpt_gui --mock-style ngram   # mock replies from data/sample.txt
    python -m fgpt_gui --transport serial --serial-port /dev/ttyUSB0
    python -m fgpt_gui --transport serial --serial-port COM3 --mode framed
    python -m fgpt_gui --list-ports
"""

from __future__ import annotations

import argparse
import sys

from .config import GuiConfig


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="fgpt-gui",
        description="Browser chat GUI for the fpGPT FPGA language model.",
    )
    parser.add_argument("--transport", choices=("slm", "mock", "serial"), default="slm",
                        help="where replies come from (default: slm)")
    parser.add_argument("--slm-engine", choices=("microgpt", "smollm"), default="microgpt",
                        help="engine for SLM transport (default: microgpt)")
    parser.add_argument("--slm-temp", type=float, default=0.8,
                        help="temperature for SLM sampling (default: 0.8)")
    parser.add_argument("--slm-top-k", type=int, default=4,
                        help="top-k sampling for SLM (default: 4)")
    parser.add_argument("--mode", choices=("legacy", "framed"), default="legacy",
                        help="UART link protocol (default: legacy)")
    parser.add_argument("--serial-port", dest="serial_port", default=None,
                        help="serial device, e.g. /dev/ttyUSB0 or COM3")
    parser.add_argument("--baud", type=int, default=None,
                        help="override baud rate (default: from board_params)")
    parser.add_argument("--gen-tokens", type=int, default=None,
                        help="override generated bytes per prompt")
    parser.add_argument("--timeout", type=float, default=5.0,
                        help="reply inactivity timeout in seconds (default: 5)")
    parser.add_argument("--board-params", default=None,
                        help="path to board_params.vh (default: auto-discover)")
    parser.add_argument("--food-model", dest="food_model", default=None,
                        help="TFLite hot-dog model for the food tab "
                             "(default: Models/hotdog_model.tflite)")
    parser.add_argument("--mock-style", choices=("echo", "ngram"), default="echo",
                        help="mock reply style (default: echo)")
    parser.add_argument("--corpus", default=None,
                        help="corpus file for --mock-style ngram")
    parser.add_argument("--host", default="127.0.0.1",
                        help="HTTP bind address (default: 127.0.0.1)")
    parser.add_argument("--http-port", type=int, default=8765,
                        help="HTTP port (default: 8765)")
    parser.add_argument("--list-ports", action="store_true",
                        help="list serial ports and exit")
    return parser


def config_from_args(args) -> GuiConfig:
    config = GuiConfig(
        transport=args.transport,
        slm_engine=args.slm_engine,
        slm_temp=args.slm_temp,
        slm_top_k=args.slm_top_k,
        mode=args.mode,
        port=args.serial_port,
        baud=args.baud,
        gen_tokens=args.gen_tokens,
        timeout_s=args.timeout,
        board_params=args.board_params,
        food_model=args.food_model,
        mock_style=args.mock_style,
        corpus=args.corpus,
        http_host=args.host,
        http_port=args.http_port,
    )
    return config


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)

    if args.list_ports:
        from .transports.serial_transport import SerialTransport

        ports = SerialTransport.list_ports()
        print("\n".join(ports) if ports else "(no serial ports found)")
        return 0

    config = config_from_args(args)
    try:
        config.validate()
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    from .server import serve

    try:
        serve(config)
    except OSError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())