// ═══════════════════════════════════════════════════════════════
// fpGPT — Board parameters (checked-in placeholder / include target)
//
// This file is `include`d by fpga_top.v and provides the FPGPT_* macros for
// the model geometry, ROM geometry and engine requantization shifts. It is
// normally regenerated by the compiler:
//
//     python compile.py --model checkpoints/micro_gpt.pt --out build/
//     # writes build/rtl/board_params.vh
//
// and fpga/build.tcl copies that generated file over this one. The values
// below mirror the compiler's output for the default Micro-GPT shape so the
// project parses before a checkpoint has been compiled; they are NOT
// guaranteed to match a trained checkpoint.
//
// Do not hand-edit: regenerate with compile.py instead.
// ═══════════════════════════════════════════════════════════════

`ifndef FPGPT_BOARD_PARAMS_VH
`define FPGPT_BOARD_PARAMS_VH

// ── Model dimensions ──
`define FPGPT_DATA_WIDTH      8
`define FPGPT_D_MODEL         64
`define FPGPT_NUM_HEADS       4
`define FPGPT_MAX_SEQ_LEN     64
`define FPGPT_NUM_LAYERS      4
`define FPGPT_D_FF            256
`define FPGPT_VOCAB_SIZE      64

// ── Weight ROM (uniform-width image consumed by transformer_engine) ──
`define FPGPT_W_ADDR_WIDTH    18
`define FPGPT_ROM_DEPTH       212352
`define FPGPT_ROM_MEM_FILE    "weights_unified.hex"

// ── Decode configuration ──
`define FPGPT_GEN_TOKENS      16

// ── Fixed-point shifts (layer 0; engine uses one global value) ──
`define FPGPT_Q_SHIFT         6
`define FPGPT_K_SHIFT         6
`define FPGPT_V_SHIFT         7
`define FPGPT_OUT_SHIFT       7
`define FPGPT_SCORE_MULT      262144
`define FPGPT_SCORE_SHIFT     28
`define FPGPT_LN_SHIFT        7
`define FPGPT_FC1_SHIFT       6
`define FPGPT_FC2_SHIFT       8
`define FPGPT_LM_SHIFT        6

// ── Board / host interface ──
`define FPGPT_SYS_CLK_HZ      150000000
`define FPGPT_BAUD_RATE       115200

`endif // FPGPT_BOARD_PARAMS_VH
