// ═══════════════════════════════════════════════════════════════
// fpGPT — Board parameters (checked-in default / include target)
//
// This file is `include`d *inside* fpga_top.v and provides BOARD_* / ENGINE_*
// localparams. It is normally regenerated by the compiler:
//
//     python compile.py --model checkpoints/micro_gpt.pt --out build/
//     # writes build/rtl/board_params.vh
//
// and fpga/build.tcl copies that generated file over this one. The values
// below are a placeholder for the default Micro-GPT shape so the project
// parses before a checkpoint has been compiled; they are NOT guaranteed to
// match a trained checkpoint.
//
// Do not hand-edit: regenerate with compile.py instead.
// ═══════════════════════════════════════════════════════════════

// Model architecture (must match the trained checkpoint)
localparam BOARD_DATA_WIDTH   = 8;
localparam BOARD_VOCAB_SIZE   = 64;
localparam BOARD_MAX_SEQ_LEN  = 64;
localparam BOARD_D_MODEL      = 64;
localparam BOARD_NUM_HEADS    = 4;
localparam BOARD_NUM_LAYERS   = 4;
localparam BOARD_D_FF         = 256;

// Uniform-width engine ROM geometry
localparam BOARD_ROM_DEPTH    = 212352;
localparam BOARD_W_ADDR_WIDTH = 18;

// Per-stage requantization shifts (placeholder; compile.py emits measured ones)
localparam ENGINE_Q_SHIFT   = 0;
localparam ENGINE_K_SHIFT   = 0;
localparam ENGINE_V_SHIFT   = 0;
localparam ENGINE_OUT_SHIFT = 0;
localparam ENGINE_FC1_SHIFT = 0;
localparam ENGINE_FC2_SHIFT = 0;
localparam ENGINE_LM_SHIFT  = 0;

// Attention score settings (layer 0)
localparam ENGINE_SCORE_MULT  = 64;
localparam ENGINE_SCORE_SHIFT = 8;
