# ═══════════════════════════════════════════════════════════════
# fpGPT timing constraints — DE1-SoC / Cyclone V
#
# Clocks:
#   CLOCK_50  : 50 MHz board oscillator (PIN_AF14), 20 ns
#   clk_sys   : PLL output, 50 MHz * 3 = 150 MHz (~6.667 ns)
#
# FPGPT_USE_PLL must be defined in the QSF for the 150 MHz constraint to be
# meaningful; without it clk_sys follows CLOCK_50 and this SDC should be
# changed to a 20 ns period.
# ═══════════════════════════════════════════════════════════════

# Base oscillator
create_clock -name CLOCK_50 -period 20.000 [get_ports {CLOCK_50}]

# System clock generated by pll_150 (clk_sys net in fpga_top)
create_generated_clock -name clk_sys \
    -source [get_ports {CLOCK_50}] \
    -multiply_by 3 -divide_by 1 \
    [get_nets {clk_sys}]

# ── Asynchronous inputs ──
# KEY[*] reset and UART_RXD are asynchronous to clk_sys. UART_RXD is captured
# by the two-flop synchronizer in uart_rx.v, so it is a false path.
set_false_path -from [get_ports {KEY[*]}]
set_false_path -from [get_ports {UART_RXD}]

# ── UART / LED outputs ──
# UART_TXD is registered on clk_sys and sampled by an external adapter; allow a
# generous board/adapter delay. LEDs have no timing requirement.
set_output_delay -clock [get_clocks {clk_sys}] -max 8.000 [get_ports {UART_TXD}]
set_output_delay -clock [get_clocks {clk_sys}] -min 0.000 [get_ports {UART_TXD}]
set_false_path -to [get_ports {LEDR[*]}]

# Derive on-chip clock uncertainty for the PLL and registers
derive_clock_uncertainty
