// ═══════════════════════════════════════════════════════════════
// fpGPT — Banked synchronous weight ROM (M10K)
//
// The unified image is a flat, row-major byte stream. To feed a
// NUM_PES-wide output-stationary PE array, the bytes are de-interleaved
// across NUM_PES banks:
//
//     bank b holds row j for every j ≡ b (mod NUM_PES)
//
// A read presents a *bank address* `addr = (j_base / NUM_PES) * IN_FEATURES
// + i` and returns NUM_PES packed bytes, little-endian:
//
//     data[k*DATA_WIDTH +: DATA_WIDTH] = image[(j_base + k)*IN_FEATURES + i]
//
// NUM_PES = 1 reproduces the original flat ROM exactly (bank address == flat
// byte address), so existing instantiations are unchanged.
//
// Simulation reads the flat MEM_FILE and re-interleaves it into the banks.
// For NUM_PES=1, synthesis uses MEM_FILE + ".mif" (generated by build.tcl).
// Hardware packed weights use hdl/weight_cache.v, filled by the engine FSM
// from that initialized scalar ROM.
//
// NOTE: the bank memory lives in the rom_bank submodule (instantiated in the
// rom_sync generate). Memory arrays must never be declared directly inside a
// generate block: Quartus 25.1 Analysis & Synthesis hangs on that (same issue
// fixed in hdl/weight_cache.v). The de-interleave helper memory is module
// scope and behind `synthesis translate_off` so Quartus never sees it.
// ═══════════════════════════════════════════════════════════════

module rom_bank #(
    parameter DATA_WIDTH  = 8,
    parameter NUM_PES     = 1,
    parameter BANK        = 0,
    parameter IN_FEATURES = 1,
    parameter DEPTH       = 65536,
    parameter BANK_DEPTH  = 65536,
    parameter BANK_AW     = 16,
    parameter MEM_FILE    = "weights.hex"
) (
    input  wire                         clk,
    input  wire [BANK_AW-1:0]           rd_addr,
    output reg  signed [DATA_WIDTH-1:0] q
);
    // build.tcl generates this MIF from the same validated hex image used
    // by simulation. Explicit MIF binding avoids expanding a large HDL
    // initialization block during Quartus elaboration.
    localparam INIT_FILE = (NUM_PES == 1) ? {MEM_FILE, ".mif"} : "";
    (* ramstyle = "M10K", ram_init_file = INIT_FILE *)
    reg [DATA_WIDTH-1:0] mem [0:BANK_DEPTH-1];

    // Synchronous read of this bank.
    always @(posedge clk)
        q <= mem[rd_addr];

    // Simulation initialization. Hardware initialization is provided by
    // ram_init_file above, including for the scalar board source ROM.
    // synthesis translate_off
    reg [DATA_WIDTH-1:0] flat [0:DEPTH-1];
    integer f, j, i;
    initial begin
        if (NUM_PES == 1) begin
            $readmemh(MEM_FILE, mem);
        end else begin
            $readmemh(MEM_FILE, flat);
            for (f = 0; f < DEPTH; f = f + 1) begin
                j = f / IN_FEATURES;
                i = f % IN_FEATURES;
                if ((j % NUM_PES) == BANK)
                    mem[(j / NUM_PES) * IN_FEATURES + i] = flat[f];
            end
        end
    end
    // synthesis translate_on
endmodule


module rom_sync #(
    parameter DATA_WIDTH  = 8,
    parameter NUM_PES     = 1,
    parameter IN_FEATURES = 1,      // bytes per weight row (power of two)
    parameter ADDR_WIDTH  = 16,
    parameter DEPTH       = 65536,  // flat image bytes
    parameter MEM_FILE    = "weights.hex"
) (
    input  wire                          clk,
    input  wire [ADDR_WIDTH-1:0]         addr,   // bank address
    output wire signed [NUM_PES*DATA_WIDTH-1:0] data
);
    localparam IN_SHIFT   = (IN_FEATURES <= 1) ? 0 : $clog2(IN_FEATURES);
    localparam P_SHIFT    = (NUM_PES <= 1) ? 0 : $clog2(NUM_PES);
    localparam ROWS       = (DEPTH + IN_FEATURES - 1) / IN_FEATURES;
    localparam BANK_ROWS  = (ROWS + NUM_PES - 1) / NUM_PES;
    localparam BANK_DEPTH = BANK_ROWS * IN_FEATURES;
    localparam BANK_AW    = (BANK_DEPTH <= 1) ? 1 : $clog2(BANK_DEPTH);

    // Flat read address addr = j_base*IN_FEATURES + i -> bank address
    // (j_base / NUM_PES) * IN_FEATURES + i. NUM_PES == 1 is the identity.
    wire [ADDR_WIDTH:0] r_j     = addr >> IN_SHIFT;
    wire [ADDR_WIDTH:0] r_i     = addr & (IN_FEATURES - 1);
    wire [BANK_AW-1:0]  rd_addr = ((r_j >> P_SHIFT) << IN_SHIFT) | r_i;

    genvar b;
    generate
        for (b = 0; b < NUM_PES; b = b + 1) begin : bank
            wire signed [DATA_WIDTH-1:0] q;

            rom_bank #(
                .DATA_WIDTH(DATA_WIDTH), .NUM_PES(NUM_PES), .BANK(b),
                .IN_FEATURES(IN_FEATURES), .DEPTH(DEPTH),
                .BANK_DEPTH(BANK_DEPTH), .BANK_AW(BANK_AW),
                .MEM_FILE(MEM_FILE)
            ) u_bank (
                .clk(clk), .rd_addr(rd_addr), .q(q)
            );

            assign data[b*DATA_WIDTH +: DATA_WIDTH] = q;
        end
    endgenerate

endmodule
